### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by naturecodevoid** [DBTDerpbox/Legacy-Edition-Battle#30]
Hi, is there a Discord? If not, I think it would be a good tool for discussing the legacy edition minigame remakes. I couldn't find a link anywhere. I'm interested in making a custom plugin for this project, which would implement the same things as the custom mods while allowing the user to use server software such as PaperMC and PurpurMC, which provide much better performance.

**Comment by DBTDerpbox** [comment]
There is a discord that exists, though it has very limited invites due to the constant raiding that occurs when invites are public

the server runs on fabric, so a plugin would essentially mean an entire rewrite of the project, which i also dont know java at the moment so i would not be able to work on the code for a while

if you're interested in a discord invite get back to me and i'll send one

**Comment by naturecodevoid** [comment]
Yeah I'm interested, you could just make a verification system to combat raids and also, you can make it a "community" discord server and members have to read and agree to the rules before joining

If you want to DM it to me, my discord is naturecodevoid#6253 but I have friend requests off for everyone to prevent spam

**Comment by naturecodevoid** [comment]
Also, I believe it would be possible to replace the mods with a plugin because I can simply replicate the behavior of the mods and commands on the plugin, if done correctly it would require 0 work of the datapack side and you wouldn't need to learn java because I would make the plugin, similar to how Kyrptonaught made the mods

**Comment by DBTDerpbox** [comment]
https://discord.gg/jX46j27S
